### ISSUE TITLE
Error: 14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by LAMike310** [wbobeirne/lightning-app-tutorial#1]
I'm having trouble getting the first part of this tutorial working

.env file:

```
# Server configuration
PORT=3000

# LND Node configuration
LND_GRPC_URL="127.0.0.1:10009"

LND_MACAROON="_________XqqBPvvUS0wxZ1R6q7xIBMBoPCgdhZGRyZXNzEgRyZWFkGgwKBGluZm8SBHJlYWQaEAoIaW52b2ljZXMSBHJlYWQaDwoHbWVzc2FnZRIEcmVhZBoQCghvZmZjaGFpbhIEcmVhZBoPCgdvbmNoYWluEgRyZWFkGg0KBXBlZXJzEgRyZWFkAAAGICN/5z7nv+MOUPrdBuDqQGPmU6+Gp7wsGCE________"

LND_TLS_CERT="________0FURS0tLS0tCk1JSUNnRENDQWlhZ0F3SUJBZ0lRWE1KZ0VaSUlkVzJTbDhHSEdWM2YwekFLQmdncWhrak9QUVFEQWpCR01SOHcKSFFZRFZRUUtFeFpzYm1RZ1lYVjBiMmRsYm1WeVlYUmxaQ0JqWlhKME1TTXdJUVlEVlFRREV4cE5hV05vWVdWcwpjeTFOWVdOQ2IyOXJMVkJ5Ynk1c2IyTmhiREFlRncweE9UQTFNVGN3TVRNMU1EQmFGdzB5TURBM01URXdNVE0xCk1EQmFNRVl4SHpBZEJnTlZCQW9URm14dVpDQmhkWFJ2WjJWdVpYSmhkR1ZrSUdObGNuUXhJekFoQmdOVkJBTVQKR2sxcFkyaGhaV3h6TFUxaFkwSnZiMnN0VUhKdkxteHZZMkZzTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRURUYzJ1cGRKVXA0U2J0QXBpQ0ZMOWtERFFpS21jaUo1ajJ4bm1vUmJCbHV2bFVqRmFBU1JPeS9kCmxaNnIvRWxOUWhub1pVNzZEeU5TRnZTb1ZaYmtkYU9COVRDQjhqQU9CZ05WSFE4QkFmOEVCQU1DQXFRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96Q0J6Z1lEVlIwUkJJSEdNSUhEZ2hwTmFXTm9ZV1ZzY3kxTllXTkNiMjlyTFZCeQpieTVzYjJOaGJJSUpiRzlqWVd4b2IzTjBnZ1IxYm1sNGdncDFibWw0Y0dGamEyVjBod1IvQUFBQmh4QUFBQUFBCkFBQUFBQUFBQUFBQUFBQUJoeEQrZ0FBQUFBQUFBQUFBQUFBQUFBQUJoeEQrZ0FBQUFBQUFBQXdWYWpDemFJaXMKaHdUQXFBQm5oeEQrZ0FBQUFBQUFBT1M1a1AvK3ovQ2JoeEQrZ0FBQUFBQUFBS2FKUWRnMkl2eHFoeEQrZ0FBQQpBQUFBQUhRZUNZbVF2RkF3aHhEK2dBQUFBQUFBQUU4N1J2QndKU1JKTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDCklRQ3FNNlp6Q0VTdFlqWVdPR2Q3UjZ4ckR1MDI2YUliRnN2d29mVTZObVBrQWdJZ0c1bXhVV3h3QkhxNlJhdlQKcUFRUUFCdUZkTWZ1ZExadHExV051MjQ3TVNVPQotLS0tLUVORCBDRVJUS_________"

```

- MacOS
- NodeLauncher

Error I got when going to `http://localhost:3000/`

```
Initializing Lightning node...
(node:1703) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Lightning node initialized!
Starting server...
Server started at http://localhost:3000!
Error: 14 UNAVAILABLE: failed to connect to all addresses
    at Object.exports.createStatusError (/Users/mike/Desktop/Code/May/lightning-app-tutorial/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/mike/Desktop/Code/May/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/mike/Desktop/Code/May/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/mike/Desktop/Code/May/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/mike/Desktop/Code/May/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:845:24)
```

Any idea on what I'm doing wrong? Don't see much I could've messed up other than entering in something wrong with the `LND_GRPC_URL` variable

**Comment by LAMike310** [comment]
Figured it out, it was the `LND_GPRC_URL` that I was messing up. I'm using NodeLauncher, and I found the correct port by going to the "Advanced" tab on that toolbar


<img width="369" alt="Screen Shot 2019-05-30 at 6 30 36 PM" src="https://user-images.githubusercontent.com/2181637/58675443-38a82a00-8309-11e9-9e44-19731758e557.png">

For me, it was `10011`

**Comment by wbobeirne** [comment]
Glad you got it sorted. It also looks like your macaroon and cert were improperly encoded as well. Let me know if you have any other issues!

**Comment by Janaka-Steph** [comment]
Same error but I had to change  `LND_GRPC_URL="127.0.0.1:10009"` to `LND_GRPC_URL="localhost:10009"`

**Comment by emalmaraz** [comment]
I'm having the same `UNAVAILABLE: failed to connect to all addresses` error. 

I double checked the .env variables and they're all correct. The only I can think of that might be wrong is:
1) I encoded incorrectly (I did base64 [file] just like the instructions) 
2) I have various lnd installs (CLI, Node Launcher, Lightning App) and this could be an issue.

This is what my .env looks like:
```
# Server configuration
PORT=3000

# LND Node configuration
LND_GRPC_URL="localhost:10006"
LND_MACAROON="AgEDbG5kAooBAwoQiHwOnTWK1qGxMAzSJm+yJhIBMBoPCgdhZGRyZXNzEgRyZWFkGgwKBGluZm8SBHJlYWQaEAoIaW52b2ljZXMSBHJlYWQaDwoHbWVzc2FnZRIEcmVhZBoQCghvZmZjaGFpbhIEcmVhZBoPCgdvbmNoYWluEgRyZWFkGg0KBXBlZXJzEgRyZWFkAAAGIDOl6D8RNJ4vZLRslhfvGIb034Yhpf6jnQf31ut4M5NC"
LND_TLS_CERT="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNUekNDQWZTZ0F3SUJBZ0lSQU9qcmxsTXJ1VUZyUVJ4MG12bWwzSEV3Q2dZSUtvWkl6ajBFQXdJd05URWYKTUIwR0ExVUVDaE1XYkc1a0lHRjFkRzluWlc1bGNtRjBaV1FnWTJWeWRERVNNQkFHQTFVRUF4TUpSVzF0ZVhNdApUVUpRTUI0WERURTVNRFV6TURFNU1UUXdOMW9YRFRJd01EY3lOREU1TVRRd04xb3dOVEVmTUIwR0ExVUVDaE1XCmJHNWtJR0YxZEc5blpXNWxjbUYwWldRZ1kyVnlkREVTTUJBR0ExVUVBeE1KUlcxdGVYTXRUVUpRTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXRUZzVFNGlFL0ZHaXFZVHpuQ1E1eC9xNnRLVk4xcnc2Y0gydwplZGZ5K2JFNVA5M3VUQnVIZHZNb1dWSkhBUUhwcDY5dG5XQnhUUjRpRHYwN3BwUXh5Nk9CNURDQjRUQU9CZ05WCkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96Q0J2UVlEVlIwUkJJRzFNSUd5Z2dsRmJXMTUKY3kxTlFsQ0NDV3h2WTJGc2FHOXpkSUlFZFc1cGVJSUtkVzVwZUhCaFkydGxkSWNFZndBQUFZY1FBQUFBQUFBQQpBQUFBQUFBQUFBQUFBWWNRL29BQUFBQUFBQUFBQUFBQUFBQUFBWWNRL29BQUFBQUFBQUFZN0VycksrTGJnSWNFCndLZ0JSb2NRSmdBWEFnK0FiNkFZbzJKWkp6YUk2NGNRSmdBWEFnK0FiNkFVVlNSZkw2VXNxWWNRL29BQUFBQUEKQUFCQTFUSC8vaUY3VlljUS9vQUFBQUFBQUFEYlphUHFNdmJJNnpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQQp2MmdGV29NSTJBbE41WDNWSmxZY2xBRFRQVjdtUWdTNll0a1d3UC9SanJnQ0lRQ3UwbGpuaUlhMXo3TjJCeVAyCjN0TTBLazFWc0VSK2toNXJYVHh2VlV0Wk5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
```

**Comment by ealmz** [comment]
I'm having the same `UNAVAILABLE: failed to connect to all addresses` error. 

I double checked the .env variables and they're all correct. The only I can think of that might be wrong is:
1) I encoded incorrectly (I did base64 [file] just like the instructions) 
2) I have various lnd installs (CLI, Node Launcher, Lightning App) and this could be an issue.

This is what my .env looks like:
```
# Server configuration
PORT=3000

# LND Node configuration
LND_GRPC_URL="localhost:10006"
LND_MACAROON="AgEDbG5kAooBAwoQiHwOnTWK1qGxMAzSJm+yJhIBMBoPCgdhZGRyZXNzEgRyZWFkGgwKBGluZm8SBHJlYWQaEAoIaW52b2ljZXMSBHJlYWQaDwoHbWVzc2FnZRIEcmVhZBoQCghvZmZjaGFpbhIEcmVhZBoPCgdvbmNoYWluEgRyZWFkGg0KBXBlZXJzEgRyZWFkAAAGIDOl6D8RNJ4vZLRslhfvGIb034Yhpf6jnQf31ut4M5NC"
LND_TLS_CERT="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNUekNDQWZTZ0F3SUJBZ0lSQU9qcmxsTXJ1VUZyUVJ4MG12bWwzSEV3Q2dZSUtvWkl6ajBFQXdJd05URWYKTUIwR0ExVUVDaE1XYkc1a0lHRjFkRzluWlc1bGNtRjBaV1FnWTJWeWRERVNNQkFHQTFVRUF4TUpSVzF0ZVhNdApUVUpRTUI0WERURTVNRFV6TURFNU1UUXdOMW9YRFRJd01EY3lOREU1TVRRd04xb3dOVEVmTUIwR0ExVUVDaE1XCmJHNWtJR0YxZEc5blpXNWxjbUYwWldRZ1kyVnlkREVTTUJBR0ExVUVBeE1KUlcxdGVYTXRUVUpRTUZrd0V3WUgKS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXRUZzVFNGlFL0ZHaXFZVHpuQ1E1eC9xNnRLVk4xcnc2Y0gydwplZGZ5K2JFNVA5M3VUQnVIZHZNb1dWSkhBUUhwcDY5dG5XQnhUUjRpRHYwN3BwUXh5Nk9CNURDQjRUQU9CZ05WCkhROEJBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96Q0J2UVlEVlIwUkJJRzFNSUd5Z2dsRmJXMTUKY3kxTlFsQ0NDV3h2WTJGc2FHOXpkSUlFZFc1cGVJSUtkVzVwZUhCaFkydGxkSWNFZndBQUFZY1FBQUFBQUFBQQpBQUFBQUFBQUFBQUFBWWNRL29BQUFBQUFBQUFBQUFBQUFBQUFBWWNRL29BQUFBQUFBQUFZN0VycksrTGJnSWNFCndLZ0JSb2NRSmdBWEFnK0FiNkFZbzJKWkp6YUk2NGNRSmdBWEFnK0FiNkFVVlNSZkw2VXNxWWNRL29BQUFBQUEKQUFCQTFUSC8vaUY3VlljUS9vQUFBQUFBQUFEYlphUHFNdmJJNnpBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQQp2MmdGV29NSTJBbE41WDNWSmxZY2xBRFRQVjdtUWdTNll0a1d3UC9SanJnQ0lRQ3UwbGpuaUlhMXo3TjJCeVAyCjN0TTBLazFWc0VSK2toNXJYVHh2VlV0Wk5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
```

**Comment by wbobeirne** [comment]
@ealmz your gRPC url seems to indicate you're trying to connect to the Lightning App install, not the node launcher or CLI. Are you sure the macaroon and certs you provided are from the folder for Lightning App? And is the app running?

Also just as an aside to you and anyone who else might post: if you post your macaroons here in full plain text, make sure you regenerate your macaroons at some point before you ever expose your node online. Someone nefarious and dedicated could try to access your node!

**Comment by ealmz** [comment]
I overlooked the app running. Thank you @wbobeirne!
