### ISSUE TITLE
Error: 14 UNAVAILABLE: Empty update

### ISSUE THREAD

**Issue by CabtonWithaK** [wbobeirne/lightning-app-tutorial#12]
Hi, I am trying to connect to my LND node on my LunaNode server, but am experiencing some difficulties

I am getting this error when I try to display my node info using `npm run dev` 

this is the error:
`E1215 21:18:57.672958000 140735946343296 ssl_transport_security.cc:643] Could not load any root certificate.
E1215 21:18:57.673252000 140735946343296 ssl_transport_security.cc:1703] Cannot load server root certificates.
E1215 21:18:57.673289000 140735946343296 ssl_security_connector.cc:112] Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E1215 21:18:57.673320000 140735946343296 secure_channel_create.cc:132] Failed to create secure subchannel for secure name '170.75.163.21:11009'
E1215 21:18:57.673335000 140735946343296 secure_channel_create.cc:50]  Failed to create channel args during subchannel creation.
Error: 14 UNAVAILABLE: Empty update
    at Object.exports.createStatusError (/Users/johandegrieck/projects/bitcoinlightningapps/lightning-app-tutorial/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/johandegrieck/projects/bitcoinlightningapps/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/johandegrieck/projects/bitcoinlightningapps/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/johandegrieck/projects/bitcoinlightningapps/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/johandegrieck/projects/bitcoinlightningapps/lightning-app-tutorial/node_modules/grpc/src/client_interceptors.js:847:24)`

I am pretty sure my readonly macaroon and tls.cert are properly base64 encoded
I am not sure, however if my LND_GRPC_URL is correctly set...

my .env looks like this:

`
PORT=3000

LND_GRPC_URL="[myExternalipv4address]:11009"
LND_MACAROON="M...U2"
LND_TLS_CERT="T....09"
` 
any help greatly appreciated!

**Comment by CabtonWithaK** [comment]
UPDATE: The problem was that I used the readonly macaroon string from my BTCPay server settings. I now properly base64 encoded my readonly.macaroon-file and tls.cert and now I no longer get this specific error message. 

I now get the error "Error: 14 UNAVAILABLE: failed to connect to all addresses"
I guess I'm now one step closer to victory! ^^

**Comment by pparonson** [comment]
@johandegrieck I am trying to get this to connect to a raspiblitz node.  I'm getting the same "Error: 14 UNAVAILABLE: failed to connect to all addresses" in the terminal console and "api.ts:55 WebSocket connection to 'ws://localhost:3001/api/posts' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED" in the browser console. Any help appreciated. Thanks.
