### ISSUE TITLE
Part 2: Errors when trying to run

### ISSUE THREAD

**Issue by MrPaz** [wbobeirne/lightning-app-tutorial#4]
Once I get the .env file set up properly, I keep getting errors at 'npm run dev'.  I'm using Zap on Windows 10.   Zap is sync'd.  

Here is my .env file:
```
# Server configuration
PORT=3001

# LND Node configuration
LND_GRPC_URL="127.0.0.1:11009"

API_PATH="http://localhost:3001/api"

##C:\Users\mattp\AppData\Roaming\Zap\lnd\bitcoin\testnet\wallet-1\data\chain\bitcoin\testnet\readonly.macaroon
#LND_MACAROON="AgEDbG5kAooBAwoQKr5WpHMp+hFXL5zw+iHKhhIBMBoPCgdhZGRyZXNzEgRyZWFkGgwKBGluZm8SBHJlYWQaEAoIaW52b2ljZXMSBHJlYWQaDwoHbWVzc2FnZRIEcmVhZBoQCghvZmZjaGFpbhIEcmVhZBoPCgdvbmNoYWluEgRyZWFkGg0KBXBlZXJzEgRyZWFkAAAGILHIxP5rxegFfOhRAF+qQdaacotDfa1MQPbjWy6q8+nz"

##C:\Users\mattp\AppData\Roaming\Zap\lnd\bitcoin\testnet\wallet-1\data\chain\bitcoin\testnet\invoice.macaroon
LND_MACAROON="AgEDbG5kAkcDChApvlakcyn6EVcvnPD6IcqGEgEwGhYKB2FkZHJlc3MSBHJlYWQSBXdyaXRlGhcKCGludm9pY2VzEgRyZWFkEgV3cml0ZQAABiA8JNx5gjHOTruwwFU8ljXnv8p8b8jhX2V9DKNjSW0WXQ=="

##C:\Users\mattp\AppData\Roaming\Zap\lnd\bitcoin\testnet\wallet-1>tls.cert
LND_TLS_CERT="MIICejCCAiCgAwIBAgIRAL6yn6OkIGJy8mIr4tIaAiwwCgYIKoZIzj0EAwIwMTEfMB0GA1UEChMWbG5kIGF1dG9nZW5lcmF0ZWQgY2VydDEOMAwGA1UEAxMFTXJQYXowHhcNMTkwNTI4MjMyMDI4WhcNMjAwNzIyMjMyMDI4WjAxMR8wHQYDVQQKExZsbmQgYXV0b2dlbmVyYXRlZCBjZXJ0MQ4wDAYDVQQDEwVNclBhejBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKA4cW1/7Pf4CRKAgl3NRKAh7vMOIy3IEQwxYgX0446NCF3s35x0q3ufdlI/amveHGjD0T9ehlE9+VeupD+Z3vGjggEXMIIBEzAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB/zCB7wYDVR0RBIHnMIHkggVNclBheoIJbG9jYWxob3N0ggR1bml4ggp1bml4cGFja2V0hwR/AAABhxAAAAAAAAAAAAAAAAAAAAABhxD+gAAAAAAAAByJ5OL4bSHIhwQKcygahxD+gAAAAAAAABBArqpURD3KhwSp/j3KhxD+gAAAAAAAAJkkU2TUikmKhwQKAEsBhxD+gAAAAAAAAMAupyC78XEFhwSp/nEFhxD+gAAAAAAAAKCRlBmfJ9UahwSp/tUahxD+gAAAAAAAACC1IQ8hyBIHhwQKh/5DhxD+gAAAAAAAAASxMBbCVoVLhwTAqE6RMAoGCCqGSM49BAMCA0gAMEUCIQCiZsvY4q45qi9p/XRRaj999y9lw2UOLyo3VKsGiQSTqAIgSqZ1YhvUWbPuilrj/Rt2cPfiYVQTc7IWoPwfowLJZp4="
```

Here is the output in the terminal:
```
C:\Users\mattp\Documents\Dev\chicago-bob-lapp>npm run dev

> ln-sample-app@0.1.0 dev C:\Users\mattp\Documents\Dev\chicago-bob-lapp
> concurrently -n server,client 'npm run dev:server' 'npm run dev:client'

[server] 'np' is not recognized as an internal or external command,
[server] operable program or batch file.
[client] 'run' is not recognized as an internal or external command,
[client] operable program or batch file.
[2] The filename, directory name, or volume label syntax is incorrect.
[3] 'np' is not recognized as an internal or external command,
[3] operable program or batch file.
[4] 'run' is not recognized as an internal or external command,
[4] operable program or batch file.
[5] The filename, directory name, or volume label syntax is incorrect.
[3] np exited with code 1
[2] dev:server' exited with code 1
[client] run exited with code 1
[server] np exited with code 1
[5] dev:client' exited with code 1
[4] run exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ln-sample-app@0.1.0 dev: `concurrently -n server,client 'npm run dev:server' 'npm run dev:client'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ln-sample-app@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mattp\AppData\Roaming\npm-cache\_logs\2019-07-02T13_54_25_444Z-debug.log

```

See anything amiss / any ideas?

**Comment by MrPaz** [comment]
Here is the contents of the debug.log referenced above:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle ln-sample-app@0.1.0~predev: ln-sample-app@0.1.0
6 info lifecycle ln-sample-app@0.1.0~dev: ln-sample-app@0.1.0
7 verbose lifecycle ln-sample-app@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle ln-sample-app@0.1.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\mattp\Documents\Dev\chicago-bob-lapp\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\Git\cmd;C:\Users\mattp\Desktop\Tools\Crypto\electrum-personal-server-eps-v0.1.6\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\mattp\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\mattp\AppData\Local\Programs\Python\Python37-32\;C:\Users\mattp\AppData\Local\Microsoft\WindowsApps;C:\Users\mattp\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mattp\.dotnet\tools;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Users\mattp\AppData\Roaming\npm
9 verbose lifecycle ln-sample-app@0.1.0~dev: CWD: C:\Users\mattp\Documents\Dev\chicago-bob-lapp
10 silly lifecycle ln-sample-app@0.1.0~dev: Args: [ '/d /s /c',
10 silly lifecycle   'concurrently -n server,client \'npm run dev:server\' \'npm run dev:client\'' ]
11 silly lifecycle ln-sample-app@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle ln-sample-app@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: ln-sample-app@0.1.0 dev: `concurrently -n server,client 'npm run dev:server' 'npm run dev:client'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid ln-sample-app@0.1.0
15 verbose cwd C:\Users\mattp\Documents\Dev\chicago-bob-lapp
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error ln-sample-app@0.1.0 dev: `concurrently -n server,client 'npm run dev:server' 'npm run dev:client'`
22 error Exit status 1
23 error Failed at the ln-sample-app@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by wbobeirne** [comment]
Hey @MrPaz, thanks for the report. This looks like an issue with the Windows command prompt not taking arguments in the same way as bash would on Linux or macOS. I'll accept a PR if you can get it working by altering the commands in package.json, but alternatively you may find your development experience better overall by using Windows' Ubuntu shell as it will be more compatible with most unix-centric projects.

Sorry for the hassle!

**Comment by MrPaz** [comment]
Yeah, I saw the npm args weren't being recognized as commands... weird since it went ok on Part 1.  

Anyways, I'm on WSL now, and it's working well so far. 

Thanks!

P.S. in case any other noobs search issues for SSL errors (this got me for a few minutes):
no white space in your tls certs! (or macaroons for that matter)  `base64 tls.cert` outputs an encoded block of text; you can't just paste that in between the quotation marks, you have to delete all the carriage returns so the cert is a string on a single line in between the quotes :)
